#version: '3.3'
services:
  trainee26xxdemo1011-esistafe-cedsif-node1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - oe_f_prefix=cedsif
        - oe_uuid=202503
        - OE_CLI_SH=/usr/local/bin
        - APP_VERSION=v2026.01.01
        - BUILD_MODE=training
        - trainingID=training26XXesistafe

    image: localhost:50004/cedsif/training/esistafe26xxcedsif.gov.mz-image:v2026.01.01
    hostname: trainee26xxdemo1011-esistafe-cedsif-node1
    container_name: trainee26xxdemo1011-esistafe-cedsif-node1
    env_file: .env
    ports:
      - "1011:22"
      - "1081:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: "1.5"
#          memory: "1024MB"
#      placement:
#    	  constraints:
#      	    - node.labels.trainee.id==trainee25xxdemo1011
#      mode: "replicated"
#      replicas: "2"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "https://localhost:4000"]
#      interval: 10s
#      timeout: 5s
#      retries: 1
    networks:
      - esistafe-net

  trainee26xxdemo1011-esistafe-cedsif-node2:
    image: localhost:50004/cedsif/training/esistafe26xxcedsif.gov.mz-image:v2026.01.01
    hostname: trainee26xxdemo1011-esistafe-cedsif-node2
    container_name: trainee26xxdemo1011-esistafe-cedsif-node2
    ports:
      - "1012:22"
#    volumes:
#      - trainee26xxdemo1011-esistafe-cedsif-volume:/srv
    networks:
      - esistafe-net

networks:
 esistafe-net:
